export const MINE_BLOCK = 'MINE_BLOCK';         //used
export const GET_CHAIN = 'GET_CHAIN';        //used
export const GET_Txs = 'GET_Txs';          //used
export const CLEAR_Txs = 'CLEAR_Txs';        //used
export const ADD_Tx = 'ADD_Tx';            //used
export const DELETE_Tx = 'DELETE_Tx';      //used
export const SET_CURRENT = 'SET_CURRENT';       //used
export const CLEAR_CURRENT = 'CLEAR_CURRENT';   //used
export const UPDATE_Tx = 'UPDATE_Tx';      //used
export const FILTER_Tx = 'FILTER_Tx';     //used
export const CURRENT_BLOCK = 'CURRENT_BLOCK';  //used
export const CLEAR_FILTER = 'CLEAR_FILTER';     //used
export const FILTER_BLOCKS = 'FILTER_BLOCKS';//used
export const Tx_ERROR = 'Tx_ERROR'; //used
export const SET_ALERT = 'SET_ALERT'; //used
export const REMOVE_ALERT = 'REMOVE_ALERT';//used
