export const MINE_BLOCK = 'MINE_BLOCK';         //used
export const GET_CHAIN = 'GET_CONTACTS';        //used
export const GET_Txs = 'GET_CONTACTS';          //used
export const CLEAR_Txs = 'GET_CONTACTS';        //used
export const ADD_Tx = 'ADD_CONTACT';            //used
export const DELETE_Tx = 'DELETE_CONTACT';      //used
export const SET_CURRENT = 'SET_CURRENT';       //used
export const CLEAR_CURRENT = 'CLEAR_CURRENT';   //used
export const UPDATE_Tx = 'UPDATE_CONTACT';      //used
export const FILTER_Tx = 'FILTER_CONTACTS';     //used
export const CURRENT_BLOCK = 'CLEAR_CONTACTS';  //used
export const CLEAR_FILTER = 'CLEAR_FILTER';     //used
export const Tx_ERROR = 'CONTACT_ERROR';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';